### ISSUE TITLE
Modulo Feature

### ISSUE THREAD

**Issue by cheznewa** [thoppe/python-hyperoperators#9]
Hello It Possible To Add Modulo Parametter, For Avoid A Large Number Impossible To Calculate

And Do Not Use `a ** b % c` For Modulo Please Use `pow(a,b,c)` For Avoid Impossible Number.

Newa Our Master.

**Comment by thoppe** [comment]
Hi @cheznewa. If you'd like to add a pull request for this feature please do so and I'll add it in! I'm not currently updating this module so all updates will have to come from the community.

**Comment by cheznewa** [comment]
I Can't Get here To Done :( ù$*µ
Help-Me Or GO TO HELL!
